/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author Asus
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        glassfishButton = new javax.swing.JButton();
        javaButton = new javax.swing.JButton();
        psqlButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        glassfishLabel = new javax.swing.JLabel();
        javaeeLabel = new javax.swing.JLabel();
        psqlLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilihan Gambar");
        setUndecorated(true);

        buttonPanel.setBackground(new java.awt.Color(255, 204, 204));

        glassfishButton.setText("Glassfish");
        glassfishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glassfishButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(glassfishButton);

        javaButton.setText("JavaEE");
        javaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(javaButton);

        psqlButton.setText("PostgtreSQL");
        psqlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psqlButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(psqlButton);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        glassfishLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassfishLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\gmbr\\apps_cute-01-03-512.png")); // NOI18N
        imagePanel.add(glassfishLabel, "0");

        javaeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/javaee.png"))); // NOI18N
        imagePanel.add(javaeeLabel, "1");

        psqlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psqlLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\gmbr\\rocket.png")); // NOI18N
        imagePanel.add(psqlLabel, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void glassfishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glassfishButtonActionPerformed
        // koding glassfish
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_glassfishButtonActionPerformed

    private void javaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_javaButtonActionPerformed

    private void psqlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psqlButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_psqlButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                PilihGambarButton fullFrame = new PilihGambarButton();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
//                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton glassfishButton;
    private javax.swing.JLabel glassfishLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton javaButton;
    private javax.swing.JLabel javaeeLabel;
    private javax.swing.JButton psqlButton;
    private javax.swing.JLabel psqlLabel;
    // End of variables declaration//GEN-END:variables
}
