/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import java.awt.CardLayout;

/**
 *
 * @author Asus
 */
public class PilihGambarComboBox extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pilihanpilihCard = new javax.swing.JComboBox<>();
        exitButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        javaeeLabel = new javax.swing.JLabel();
        psqlLabel = new javax.swing.JLabel();
        glassfishLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilihan Gambar");
        setUndecorated(true);

        buttonPanel.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Pilih Gambar");
        buttonPanel.add(jLabel1);

        pilihanpilihCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glassfish", "JavaEE", "PostgtreSQL" }));
        pilihanpilihCard.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihanpilihCardItemStateChanged(evt);
            }
        });
        pilihanpilihCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanpilihCardActionPerformed(evt);
            }
        });
        buttonPanel.add(pilihanpilihCard);

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(exitButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        javaeeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/layout/javaee.png"))); // NOI18N
        imagePanel.add(javaeeLabel, "1");

        psqlLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psqlLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\gmbr\\rocket.png")); // NOI18N
        imagePanel.add(psqlLabel, "2");

        glassfishLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glassfishLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Pictures\\gmbr\\apps_cute-01-03-512.png")); // NOI18N
        imagePanel.add(glassfishLabel, "0");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pilihanpilihCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanpilihCardActionPerformed
        // TODO add your handling code here: 
        switch(pilihanpilihCard.getSelectedIndex()) {
            case 0:
                CardLayout cl0 = (CardLayout) (imagePanel.getLayout());
                cl0.show(imagePanel, "0");
                break;
            case 1:
                CardLayout cl1 = (CardLayout) (imagePanel.getLayout());
                cl1.show(imagePanel, "1");
                break;
            default:
            case 2:
                CardLayout cl2 = (CardLayout) (imagePanel.getLayout());
                cl2.show(imagePanel, "2");
                break;
 
        }
    }//GEN-LAST:event_pilihanpilihCardActionPerformed

    private void pilihanpilihCardItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihanpilihCardItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanpilihCardItemStateChanged

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel glassfishLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel javaeeLabel;
    private javax.swing.JComboBox<String> pilihanpilihCard;
    private javax.swing.JLabel psqlLabel;
    // End of variables declaration//GEN-END:variables
}
